{"packages":
    {
    "selectmirroreddoors":
        {
          "name":"SelectMirroredDoors",
          "version":"0.2.0",
          "url":"https://github.com/gtalarico/pyrevitplus/blob/master/release/pyrevitplus-0.1.0.zip",
          "files":["0100_MiscTools_PushButton_SelectMirroredDoors.png", "SelectMirroredDoors_SelectDoors.py"]
        },
    "removeunderlay":
        {
          "name":"RemoveUnderlay",
          "version":"0.2.0",
          "url":"https://github.com/gtalarico/pyrevitplus/blob/master/release/pyrevitplus-0.1.0.zip",
          "files":["0101_MiscTools_PushButton_RemoveUnderlay.png", "RemoveUnderlay_RemoveUnderlay.py"]
        },
    "openinexcel":
        {
          "name":"OpenInExcel",
          "version":"0.1.0",
          "url":"https://github.com/gtalarico/pyrevitplus/blob/master/release/pyrevitplus-0.1.0.zip",
          "files":["0102_MiscTools_PushButton_OpenInExcel.png", "OpenInExcel_OpenInExcel.py"]
        },
    "smartalign":
        {
          "name":"SmartAlign",
          "version":"0.3.0",
          "url":"https://github.com/gtalarico/pyrevitplus/blob/master/release/pyrevitplus-0.1.0.zip",
          "files": ["0001_SmartAlign_PulldownButton_Vertical.png",
                    "0002_SmartAlign_PulldownButton_Horizontal.png",
                    "Horizontal_AlignCenter.png",
                    "Horizontal_AlignCenter.py",
                    "Horizontal_AlignLeft.png",
                    "Horizontal_AlignLeft.py",
                    "Horizontal_AlignRight.png",
                    "Horizontal_AlignRight.py",
                    "SmartAlign.py",
                    "Vertical_AlignBottom.png",
                    "Vertical_AlignBottom.py",
                    "Vertical_AlignCenter.png",
                    "Vertical_AlignCenter.py",
                    "Vertical_AlignTop.png",
                    "Vertical_AlignTop.py"
                    ]
        }
    }
}
